### ISSUE TITLE
This driver does not support retrieving URLs.

### ISSUE THREAD

**Issue by datangkang123** [singlequote/laravel-webdav#1]
laravel9报错：This driver does not support retrieving URLs.

```
League\Flysystem\UnableToCheckFileExistence: Unable to check existence for: bm_5cab3e724ff2b473/ece42185e498f3f882e7cf016ab2946e.jpg in file /www/wwwroot/go.kzhgzs.cn/vendor/league/flysystem/src/UnableToCheckExistence.php on line 19

#0 /www/wwwroot/go.kzhgzs.cn/vendor/league/flysystem-webdav/WebDAVAdapter.php(78): League\Flysystem\UnableToCheckExistence::forLocation()
#1 /www/wwwroot/go.kzhgzs.cn/vendor/league/flysystem/src/Filesystem.php(49): League\Flysystem\WebDAV\WebDAVAdapter->fileExists()
#2 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(181): League\Flysystem\Filesystem->has()
#3 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Form/Field/UploadField.php(101): Illuminate\Filesystem\FilesystemAdapter->exists()
#4 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Form/Field/UploadField.php(201): Dcat\Admin\Form\Field\File->renameIfExists()
#5 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Form/Concerns/HasFiles.php(51): Dcat\Admin\Form\Field\File->upload()
#6 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Form.php(685): Dcat\Admin\Form->handleUploadFile()
#7 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Form.php(621): Dcat\Admin\Form->beforeStore()
#8 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Http/Controllers/AdminController.php(146): Dcat\Admin\Form->store()
#9 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Dcat\Admin\Http\Controllers\AdminController->store()
#10 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#11 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#12 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#13 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#14 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Http/Middleware/WebUploader.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\Admin\Http\Middleware\WebUploader->handle()
#17 /www/wwwroot/go.kzhgzs.cn/vendor/dcat/laravel-admin/src/Http/Middleware/Session.php(12): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /www/wwwroot/go.kzhgzs.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\Admin\Http\Middleware\Session->handle()
```

**Comment by wimurk** [comment]
@datangkang123 please provide examples such as code snippets

**Comment by wimurk** [comment]
@datangkang123 also the error is originated from the laravel file system. Can you share your code and configs?

**Comment by wimurk** [comment]
Closing this issue because of lack of information
